#!/usr/bin/env bash

helpFunc() {
echo Usage: $0 [Options][-f directory] 
echo -e ''
echo Search a directory for identical files, using their sha1sum.
echo -e ''
echo Options:
echo '  -f              folder path'
echo '  -h, --help      print the help'
echo '  -e              only print the extra copies of a file'
echo '  -d              the depth of the search'
echo '  -r              search recursively'
echo -e ''
}
EXTRA=False
RECURSIVE=False
DIRECTORY=.
DEPTH=1
while getopts ":ehrd:f:" opt; do
	case "${opt}" in
		f)
			DIRECTORY=$OPTARG
			[ ! -d $DIRECTORY ] && echo $0: $DIRECTORY is not a directory && exit 1
			;;
		e)
			EXTRA=1
			;;
			
		:)
			echo "Invalid option: -$OPTARG requires an argument" 1>&2
			exit 3
			;;
		\?)
			echo "Invalid option: -$OPTARG" 1>&2
			exit 4
			;;
		d)
			DEPTH=$OPTARG
			[ $OPTARG -gt 0 ]  2> /dev/null
			if [ $? -ne 0 ]; then
				 echo $0: Invalid argument $OPTARG for option d
				 exit 2;
			fi
			;;
		r)
			RECURSIVE=True
			;;
		h)
			helpFunc	
			exit 0
			;;
		*)
			helpFunc
			exit 5
			;;
	esac
done
shift $((OPTIND-1))

if [ $RECURSIVE = True ]; then
        # Gathering files and sha1sums in a variable
	FILES_SHASUMS=$(find "$DIRECTORY" -type f   | xargs sha1sum )
else
	# Gathering files and sha1sums in a variable
	FILES_SHASUMS=$(find "$DIRECTORY" -maxdepth $DEPTH -type f   | xargs sha1sum )
fi

for i in $(echo "$FILES_SHASUMS"| cut -f3 -d' ')
do
	#Colons surrounding the variable make the shell correctly recognize carriage returns
	MATCHED=$(echo "$FILES_SHASUMS"| fgrep $(sha1sum $i | cut -f1 -d' ') | grep -v $i |cut -f3 -d' ') 

	#Delete already scanned files and update the database
	FILES_SHASUMS=$(echo "$FILES_SHASUMS"| grep -v $i )

	if [ ! -z "$MATCHED" ]
	then

	        if [ $EXTRA -eq 0 ]
       	        then
			# Print the relative path
			echo -e ''
			realpath --relative-to=$(pwd) $i
       	        fi
		for j in $MATCHED ; do
		        realpath --relative-to=$(pwd) $j
			#Delete matched files from the database
			FILES_SHASUMS=$(echo "$FILES_SHASUMS"| grep -v $j)
		done
		
	fi
done

